name: spirograph
channels:
  - conda-forge
dependencies:
  - pandoc
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx_rtd_theme >=1.0
  - sphinxcontrib-napoleon
  - ipykernel
  - jupyter_client
  - xclim
